- name: Setup frontend
  hosts: all
  become: yes # while running your code you need be root user. so you use sudo in shell scrip here we use become to run as root
  tasks:
    - name: Installing nginx server
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Remove directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and extract frontend content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy roboshop configuration
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: start service Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes

