- name: Installing erlang packages
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Downloading rabbitmq repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash


- name: Install rabbitmq server
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed


- - name: start service rabbitmq
    ansible.builtin.systmed:
      name: rabbitmq
      state: restarted
      enabled: yes

- name: Adding user and setting permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: Roboshop@1
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present



















