- name: Install Nodejs
  ansible.builtin.import_role:
      name: common
      tasks_from: nodejs

- name: Install mongodb_schema_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb_schema_setup



